version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"

  # # Maintain dependencies for python
  # - package-ecosystem: "pip"
  #   target-branch: "main"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
