#!/usr/bin/with-contenv bash

if [ "${PUID}" = "0" ] && [ "${PGID}" = "0" ]; then
    export C_FORCE_ROOT="true"
    export PYTHONWARNINGS="ignore::RuntimeWarning"
fi

# workdir
cd /data

echo "*** starting FlaskFarm..."
s6-setuidgid abc \
    python -m flaskfarm.main \
        --repeat=${FF_REPEAT} \
        --config=${FF_CONFIG}

EXITCODE=$?
echo "*** FlaskFarm exited with code ${EXITCODE}"
if [ "$EXITCODE" = "0" ]; then
    echo '*** terminating all services...'
    s6-svscanctl -t /var/run/service
else
    echo "*** restarting services..."
    printf $(expr $FF_REPEAT + 1) > /var/run/s6/container_environment/FF_REPEAT
    /etc/cont-init.d/20-config
fi
